# Generated by Django 3.0.2 on 2020-10-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='br',
            options={'ordering': ['-published'], 'verbose_name': 'Яркость', 'verbose_name_plural': 'Таблица яркости'},
        ),
        migrations.AlterField(
            model_name='br',
            name='bright',
            field=models.CharField(max_length=50, verbose_name='Яркость'),
        ),
        migrations.AlterField(
            model_name='br',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='br',
            name='time',
            field=models.CharField(max_length=50, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='br',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='br',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.Rubric', verbose_name='Рубрика'),
        ),
    ]
