# Generated by Django 3.2.5 on 2021-07-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Image',
        ),
    ]
