# Generated by Django 3.2.5 on 2021-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20210720_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_list', models.CharField(max_length=100)),
            ],
        ),
    ]
