# Generated by Django 3.0.2 on 2021-08-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_checkboximage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrudUser',
            new_name='BrightTime',
        ),
        migrations.RenameField(
            model_name='brighttime',
            old_name='address',
            new_name='bright_count',
        ),
        migrations.RenameField(
            model_name='brighttime',
            old_name='name',
            new_name='time_bright',
        ),
    ]
