# Generated by Django 3.0.2 on 2021-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20210806_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_count', models.CharField(max_length=100)),
            ],
        ),
    ]
