# Generated by Django 3.0.2 on 2021-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_ipconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brighttime',
            name='bright_count',
            field=models.IntegerField(blank=True),
        ),
    ]
