data = {
    "1": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "2": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "3": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "4": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "5": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "6": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "7": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "8": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "9": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "10": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "11": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
    "12": {
        "col": 95,
        "percent": 1,
        "1": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "2": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "3": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "4": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "5": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "6": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "7": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "8": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "9": {"mod_col": 11,
              "red": '',
              "green": '',
              "blue": '',
              },
        "10": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "11": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "12": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "13": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "14": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "15": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "16": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "17": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "18": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "19": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "20": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "21": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "22": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "23": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "24": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
        "25": {"mod_col": 11,
               "red": '',
               "green": '',
               "blue": '',
               },
    },
}

# data_2['1']['1']['mod_col'] = 1
# data_2['1']['1']['red'] = ''
# data_2['1']['1']['green'] = ''
# data_2['1']['1']['blue'] = ''

data_2 = {}


def create_dict_module(data_in):

    for _ in range(12):
        print(_ + 1)
        cabinet = str(_ + 1)
        data_in[cabinet] = {}
        data_in[cabinet]['col'] = 95
        data_in[cabinet]['percent'] = 1
        for module in range(1, 26, 1):
            module = str(module)
            data_in[cabinet][module] = {}
            data_in[cabinet][module]['mod_col'] = 12
            data_in[cabinet][module]['red'] = ''
            data_in[cabinet][module]['green'] = ''
            data_in[cabinet][module]['blue'] = ''
    print(data_in)
    print(data)


create_dict_module(data_2)



